### PR TITLE
Fix clippy lint `uninlined_format_args` -> `format_in_format_args`

### LINKED ISSUE #4: unknown lint: `clippy::uninlined_format_args`
https://github.com/dtolnay/dircnt/blob/b2fe42a6ea7d02175fd1c49d299c122b04b65add/src/main.rs#L6-L8

### PR DESCRIPTION
**Pull request by TheAwiteb**
Fixes #4

### CODE REVIEW

**Comment by TheAwiteb** [comment]
I think you're mean [`format_in_format_args`](https://rust-lang.github.io/rust-clippy/stable/index.html#format_in_format_args) by `uninlined_format_args` i don't know

**Review by dtolnay — COMMENTED** [review]
I'm not sure what this PR is doing. `uninlined_format_args` (https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args) is the one triggered by the code currently contained in this crate. `format_in_format_args` (https://rust-lang.github.io/rust-clippy/master/index.html#format_in_format_args) is some other lint that doesn't seem relevant here.

**Comment by TheAwiteb** [comment]
> I'm not sure what this PR is doing. `uninlined_format_args` (https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args) is the one triggered by the code currently contained in this crate. `format_in_format_args` (https://rust-lang.github.io/rust-clippy/master/index.html#format_in_format_args) is some other lint that doesn't seem relevant here.

Bad extension
image

**Comment by TheAwiteb** [comment]
Ohh, it's nightly lint, sorry for this 😅

**Pull request closed without merging**
